source_old/52100595_52100586_FINAL/KhachSan/KhachSan/Controllers/BookingController.cs
using KhachSan.Models;
using KhachSan.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using KhachSan.Extension;

namespace KhachSan.Controllers
{
    public class BookingController : Controller
    {
        private readonly QLKSContext _context;
        public BookingController(QLKSContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                var userId = (int)Convert.ToInt32(HttpContext.Session.GetString("userId"));
                var listBooking = _context.Bookings.Where(x => x.userId == userId).ToList();
                return View(listBooking);
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        public IActionResult CheckOut(double totalPrice)
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                if(HttpContext.Session.Get<List<CartServiceViewModel>>("CartService") == null && HttpContext.Session.Get<List<CartServiceViewModel>>("RoomService") == null)
                {
                    return RedirectToAction("Index","Room");
                }
                var userId = (int)Convert.ToInt32(HttpContext.Session.GetString("userId"));
                Booking booking = new Booking();
                booking.createdDate = DateTime.Now;
                booking.toTalPrice = totalPrice;
                booking.userId = userId;
                _context.Add(booking);
                _context.SaveChanges();
                var cartService = HttpContext.Session.Get<List<CartServiceViewModel>>("CartService");
                if(cartService != null)
                {
                    foreach (var service in cartService)
                    {
                        BookingServiceDetail bookingServiceDetail = new BookingServiceDetail();
                        bookingServiceDetail.bookingId = booking.Id;
                        bookingServiceDetail.serviceId = service.serviceId;
                        bookingServiceDetail.toTalPrice = service.servicePrice;
                        _context.Add(bookingServiceDetail);
                    }
                    _context.SaveChanges();
                }
                var cartRoom = HttpContext.Session.Get<List<CartRoomViewModel>>("CartRoom");
                if(cartRoom != null)
                {
                    foreach (var room in cartRoom)
                    {
                        BookingRoomDetail bookingRoomDetail = new BookingRoomDetail();
                        bookingRoomDetail.bookingId = booking.Id;
                        bookingRoomDetail.roomId = room.roomId;
                        bookingRoomDetail.checkIn = room.checkIn;
                        bookingRoomDetail.checkOut = room.checkOut;
                        bookingRoomDetail.toTalPrice = room.totalPrice;
                        _context.Add(bookingRoomDetail);
                    }
                    _context.SaveChanges();
                }
                HttpContext.Session.Remove("CartService");
                HttpContext.Session.Remove("CartRoom");
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
        public IActionResult ViewDetail(int id)
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                ViewData["bookId"] = id;
                List<BookingRoomDetail> bookingRoomDetails = new List<BookingRoomDetail>();
                bookingRoomDetails = _context.BookingsRoomDetails.Where(x => x.bookingId == id).ToList();
                ViewData["bookingRoomDetails"] = bookingRoomDetails;
                List<BookingServiceDetail> bookingServiceDetails = new List<BookingServiceDetail>();
                bookingServiceDetails = _context.BookingsServiceDetails.Where(x => x.bookingId == id).ToList();
                ViewData["bookingServiceDetails"] = bookingServiceDetails;
                return View();
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
    }
}

source_old/52100595_52100586_FINAL/KhachSan/KhachSan/Controllers/CartController.cs
using KhachSan.Extension;
using KhachSan.Models;
using KhachSan.ViewModel;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using System.Security.Authentication.ExtendedProtection;

namespace KhachSan.Controllers
{
    public class CartController : Controller
    {
        private readonly QLKSContext _context;
        public CartController(QLKSContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public List<CartRoomViewModel> getCartRooms
        {
            get
            {
                var data = HttpContext.Session.Get<List<CartRoomViewModel>>("CartRoom");
                if (data == null)
                {
                    data = new List<CartRoomViewModel>();
                }
                return data;
            }

        }
        public List<CartServiceViewModel> getCartServices
        {
            get
            {
                var data = HttpContext.Session.Get<List<CartServiceViewModel>>("CartService");
                if (data == null)
                {
                    data = new List<CartServiceViewModel>();
                }
                return data;
            }

        }
        public IActionResult AddRoom(int roomId)
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                var cartRoom = getCartRooms;
                var room = cartRoom.SingleOrDefault(s => s.roomId == roomId);
                if (room == null)
                {
                    var r = _context.Rooms.SingleOrDefault(r => r.Id == roomId);
                    room = new CartRoomViewModel
                    {
                        roomId = roomId,
                        roomName = r.name,
                        price = r.price,
                        checkIn = HttpContext.Session.Get<DateTime>("checkIn"),
                        checkOut = HttpContext.Session.Get<DateTime>("checkOut")
                    };
                    cartRoom.Add(room);
                }
                else
                {
                    DateTime checkIn = HttpContext.Session.Get<DateTime>("checkIn");
                    DateTime checkOut = HttpContext.Session.Get<DateTime>("checkOut");
                    if ((checkIn < room.checkIn && checkOut < room.checkIn) || (checkIn > room.checkOut && checkOut > room.checkOut))
                    {
                        var r = _context.Rooms.SingleOrDefault(r => r.Id == roomId);
                        var newRoom = new CartRoomViewModel
                        {
                            roomId = roomId,
                            roomName = r.name,
                            price = r.price,
                            checkIn = HttpContext.Session.Get<DateTime>("checkIn"),
                            checkOut = checkOut = HttpContext.Session.Get<DateTime>("checkOut")
                        };
                        cartRoom.Add(newRoom);
                    }
                }
                HttpContext.Session.Set("CartRoom", cartRoom);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
        public IActionResult AddService(int serviceId)
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                var cartService = getCartServices;
                var service = cartService.SingleOrDefault(s => s.serviceId == serviceId);
                if (service == null)
                {
                    var s = _context.Services.SingleOrDefault(s => s.Id == serviceId);
                    service = new CartServiceViewModel
                    {
                        serviceId = serviceId,
                        serviceName = s.name,
                        servicePrice = s.price
                    };
                    cartService.Add(service);
                }
                HttpContext.Session.Set("CartService", cartService);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
        public IActionResult RemoveFromCartService(int id)
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                var cartService = getCartServices;
                for (int i = 0; i < cartService.Count; i++)
                {
                    if (cartService[i].serviceId == id)
                    {
                        cartService.Remove(cartService[i]);
                    }
                }
                HttpContext.Session.Set("CartService", cartService);
                return RedirectToAction("Index", "Cart");
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
        public IActionResult RemoveFromCartRoom(int id, DateTime checkIn, DateTime checkOut)
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                var cartRoom = getCartRooms;
                for (int i = 0; i < cartRoom.Count; i++)
                {
                    if (cartRoom[i].roomId == id && cartRoom[i].checkIn == checkIn && cartRoom[i].checkOut == checkOut)
                    {
                        cartRoom.Remove(cartRoom[i]);
                    }
                }
                HttpContext.Session.Set("CartRoom", cartRoom);
                return RedirectToAction("Index", "Cart");
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
    }
}

source_old/52100595_52100586_FINAL/KhachSan/KhachSan/Controllers/RoomController.cs
using KhachSan.Models;
using KhachSan.Extension;
using KhachSan.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace KhachSan.Controllers
{
    public class RoomController : Controller
    {
        private readonly QLKSContext _context;
        public RoomController(QLKSContext context)
        {
            _context = context;
        }
        public IActionResult Index(int? page)
        {
            int pageSize = 6;
            int pageNumber=page==null || page<0 ? 1 : page.Value;
            var listRooms = _context.Rooms.AsNoTracking().OrderBy(x => x.Id);
            PagedList<Room> list = new PagedList<Room>(listRooms, pageNumber, pageSize);
            return View(list);
        }
        [HttpGet]
        public IActionResult SearchResult(SearchRoomViewModel vm)
        {
            TempData["Message"] = "";
            if(vm.DateFrom == null || vm.DateTo == null )
            {
                TempData["Message"] = "Không được để check in và check out trống!";
                return View();
            }
            if(vm.DateTo <= vm.DateFrom)
            {
                TempData["Message"] = "check in phải nhỏ hơn check out!";
                return View();
            }    
            HttpContext.Session.Set("checkIn", vm.DateFrom);
            HttpContext.Session.Set("checkOut", vm.DateTo);
            var roomBooked = from b in _context.BookingsRoomDetails
                             where 
                             ((vm.DateFrom >= b.checkIn) && (vm.DateFrom <= b.checkOut)) ||
                             ((vm.DateTo >= b.checkIn) && (vm.DateTo <= b.checkOut)) ||
                             ((vm.DateFrom <= b.checkIn) && (vm.DateTo >= b.checkIn) && (vm.DateTo <= b.checkOut)) ||
                             ((vm.DateFrom >= b.checkIn) && (vm.DateFrom <= b.checkOut) && (vm.DateTo >= b.checkOut)) ||
                             ((vm.DateFrom <= b.checkIn) && (vm.DateTo >= b.checkOut))
                             select b;
            var availableRooms = _context.Rooms.Where(r => !roomBooked.Any(b => b.roomId == r.Id)).ToList();
            foreach(var item in availableRooms)
            {
                if(item.numPeople >= vm.NoOfPeople)
                {
                    vm.Room.Add(item);
                }
            }
            return View(vm);
        }
    }
}

source_old/52100595_52100586_FINAL/KhachSan/KhachSan/Controllers/ServiceController.cs
using KhachSan.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace KhachSan.Controllers
{
    public class ServiceController : Controller
    {
        private readonly QLKSContext _context;
        public ServiceController(QLKSContext context)
        {
            _context = context;
        }
        public IActionResult Index(int? page)
        {
            int pageSize = 6;
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var listServices = _context.Services.AsNoTracking().OrderBy(x => x.Id);
            PagedList<Service> list = new PagedList<Service>(listServices, pageNumber, pageSize);
            return View(list);
        }
    }
}

source_old/52100595_52100586_FINAL/KhachSan/KhachSan/Views/Cart/Index.cshtml
@using Microsoft.AspNetCore.Http
@using KhachSan.Extension;
@using KhachSan.ViewModel
@{
    var cartService = Context.Session.Get<List<CartServiceViewModel>>("CartService");
    var cartRoom = Context.Session.Get<List<CartRoomViewModel>>("CartRoom");
    double totalPrice = 0.0;
}
<div class="container px-3 my-5 clearfix">
    <div class="card">
        <div class="card-header">
            <h2>Giỏ hàng của bạn</h2>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <h3>Phòng</h3>
                <table class="table table-bordered m-0">
                    <thead>
                        <tr>
                            <th class="text-center py-3 px-4">Mã phòng</th>
                            <th class="text-right py-3 px-4">Tên phòng</th>
                            <th class="text-right py-3 px-4">Giá phòng</th>
                            <th class="text-center py-3 px-4">Check in</th>
                            <th class="text-right py-3 px-4">Check out</th>
                            <th class="text-right py-3 px-4">Tổng tiền</th>
                            <th class="text-center align-middle py-3 px-0" style="width: 40px;"><a href="#" class="shop-tooltip float-none text-light" title="" data-original-title="Clear cart"><i class="ino ion-md-trash"></i></a></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (cartRoom != null)
                        {
                            @foreach (var crvm in cartRoom)
                            {

                                totalPrice += crvm.totalPrice;
                                <tr>
                                    <td class="text-right font-weight-semibold align-middle p-4">@crvm.roomId</td>
                                    <td class="text-right font-weight-semibold align-middle p-4">@crvm.roomName</td>
                                    <td class="text-right font-weight-semibold align-middle p-4">@crvm.price</td>
                                    <td class="text-right font-weight-semibold align-middle p-4">@crvm.checkIn</td>
                                    <td class="text-right font-weight-semibold align-middle p-4">@crvm.checkOut</td>
                                    <td class="text-right font-weight-semibold align-middle p-4">@crvm.totalPrice</td>
                                    <td class="text-center align-middle px-0"><a asp-asp-controller="Cart" asp-action="RemoveFromCartRoom" asp-route-id="@crvm.roomId" asp-route-checkIn="@crvm.checkIn" asp-route-checkOut="@crvm.checkOut" class="shop-tooltip close float-none text-danger" title="" data-original-title="Remove">×</a></td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                <h3>Dịch vụ</h3>
                <table class="table table-bordered m-0">
                    <thead>
                        <tr>
                            <th class="text-center py-3 px-4">Mã dịch vụ</th>
                            <th class="text-right py-3 px-4">Tên dịch vụ</th>
                            <th class="text-center py-3 px-4">Giá</th>
                            <th class="text-center align-middle py-3 px-0" style="width: 40px;">
                                <a href="#" class="shop-tooltip float-none text-light" title="" data-original-title="Clear cart"><i class="ino ion-md-trash"></i>
                                </a>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (cartService != null)
                        {
                            @foreach (var csvm in cartService)
                            {
                                totalPrice += csvm.servicePrice;
                                <tr>
                                    <td class="text-right font-weight-semibold align-middle p-4">@csvm.serviceId</td>
                                    <td class="text-right font-weight-semibold align-middle p-4">@csvm.serviceName</td>
                                    <td class="text-right font-weight-semibold align-middle p-4">@csvm.servicePrice VNĐ</td>
                                    <td class="text-center align-middle px-0">
                                        <a asp-asp-controller="Cart" asp-action="RemoveFromCartService" asp-route-id="@csvm.serviceId" class="shop-tooltip close float-none text-danger" title="" data-original-title="Remove">×
                                        </a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
            <div class="d-flex flex-wrap justify-content-between align-items-center pb-4">
                <div class="mt-4">
                </div>
                <div class="d-flex">
                    <div class="text-right mt-4">
                        <label class="text-muted font-weight-normal m-0">Tổng tiền</label>
                        <div class="text-large"><strong>@totalPrice VNĐ</strong></div>
                    </div>
                </div>
            </div>
            <div class="float-right">
                <a asp-controller="Room" asp-action="SearchResult" type="button" class="btn btn-lg btn-default md-btn-flat mt-2 mr-3">Tiếp tục đặt phòng</a>
                <a asp-controller="Service" asp-action="Index" type="button" class="btn btn-lg btn-default md-btn-flat mt-2 mr-3">Tiếp tục đặt dịch vụ</a>
                <a asp-controller="Booking" asp-action="CheckOut" asp-route-totalPrice="@totalPrice" type="button" class="btn btn-lg btn-primary mt-2">Xác nhận đặt</a>
            </div>
        </div>
    </div>
</div>